"""Context Router: generate minimal but accurate context for a given task."""

from __future__ import annotations

import json
from pathlib import Path

from pydantic import BaseModel, Field

from repoctx.llm.client import LLMClient
from repoctx.llm.pipeline import PromptPipeline
from repoctx.loader import (
    load_capability_index,
    load_config,
    load_protected_core_index,
)
from repoctx.models import RepoCtxConfig
from repoctx.utils.project import find_project_root


class ContextReport(BaseModel):
    """Structured context report generated by the Context Router."""

    related_modules: list[str] = Field(default_factory=list)
    key_files: list[str] = Field(default_factory=list)
    reusable_capabilities: list[str] = Field(default_factory=list)
    protected_cores: list[str] = Field(default_factory=list)
    risk_points: list[str] = Field(default_factory=list)
    suggested_tests: list[str] = Field(default_factory=list)


class ContextRouter:
    """Routes a natural-language task to the relevant project context."""

    def __init__(self, project_root: Path | None = None) -> None:
        if project_root is None:
            project_root = find_project_root()
        self.project_root = project_root.resolve()
        self.config: RepoCtxConfig = load_config(self.project_root)

    def _load_knowledge_summary(self) -> dict[str, str]:
        """Load a concise summary of the knowledge graph for prompt filling."""
        index_path = self.project_root / ".repograph" / "index.json"
        modules_summary = ""
        files_summary = ""

        if index_path.exists():
            try:
                with open(index_path, encoding="utf-8") as f:
                    index = json.load(f)
                module_names = index.get("modules", [])
                modules_summary = "\n".join(f"- {m}" for m in module_names)

                # Collect files per module
                module_files: dict[str, list[str]] = {m: [] for m in module_names}
                modules_dir = self.project_root / ".repograph" / "modules"
                if modules_dir.exists():
                    for mod_name in module_names:
                        mod_file = modules_dir / f"{mod_name}.json"
                        if mod_file.exists():
                            with open(mod_file, encoding="utf-8") as f:
                                mod_data = json.load(f)
                            for fp in mod_data.get("files", []):
                                module_files[mod_name].append(fp)

                file_lines: list[str] = []
                for mod_name, files in module_files.items():
                    if files:
                        file_lines.append(f"{mod_name}:")
                        for fp in files[:20]:  # cap per module to avoid bloat
                            file_lines.append(f"  - {fp}")
                files_summary = "\n".join(file_lines)
            except (OSError, json.JSONDecodeError):
                pass

        return {
            "modules": modules_summary or "(no modules indexed)",
            "files": files_summary or "(no files indexed)",
        }

    def _load_protected_cores_text(self) -> str:
        """Load protected core entries as plain text."""
        try:
            index = load_protected_core_index(self.project_root)
        except Exception:
            return "(no protected core index)"
        if not index.cores:
            return "(no protected cores defined)"
        lines: list[str] = []
        for core in index.cores:
            lines.append(f"- {core.name} ({core.type}): {core.description}")
        return "\n".join(lines)

    def _load_capabilities_text(self) -> str:
        """Load reusable capabilities as plain text."""
        try:
            index = load_capability_index(self.project_root)
        except Exception:
            return "(no capability index)"
        if not index.capabilities:
            return "(no reusable capabilities defined)"
        lines: list[str] = []
        for cap in index.capabilities:
            entry = cap.entry_points[0] if cap.entry_points else None
            entry_info = f" -> {entry.file_path}:{entry.function_name}" if entry else ""
            lines.append(f"- {cap.name}: {cap.description}{entry_info}")
        return "\n".join(lines)

    def _load_principles_text(self) -> str:
        """Load engineering constitution principles as plain text."""
        rules_path = self.project_root / ".repograph" / "rules" / "engineering_constitution.yaml"
        if not rules_path.exists():
            return "(no engineering constitution defined)"
        try:
            from repoctx.utils.yaml_io import load_yaml

            data = load_yaml(rules_path)
            principles = data.get("principles", [])
            lines: list[str] = []
            for p in principles:
                lines.append(f"- {p.get('id', '?')}: {p.get('statement', '')}")
            return "\n".join(lines)
        except Exception:
            return "(unable to load principles)"

    def generate(self, task_description: str) -> ContextReport:
        """Generate a context report for the given task.

        Args:
            task_description: Natural language description of the task.

        Returns:
            Structured context report.

        Raises:
            ValueError: If the task description is too vague.
        """
        task_clean = task_description.strip()
        if len(task_clean) < 3:
            raise ValueError(
                "Task description is too vague. Please provide more details, "
                "e.g. 'change free call login timing'."
            )

        summary = self._load_knowledge_summary()
        protected = self._load_protected_cores_text()
        capabilities = self._load_capabilities_text()
        principles = self._load_principles_text()

        client = LLMClient(self.config.model_provider, api_key=self.config.get_api_key())
        pipeline = PromptPipeline(client)

        template_path = Path(__file__).parent / "prompts" / "context_router.txt"

        report = pipeline.run(
            template_path=template_path,
            variables={
                "task_description": task_clean,
                "modules": summary["modules"],
                "files": summary["files"],
                "protected_cores": protected,
                "capabilities": capabilities,
                "principles": principles,
            },
            output_model=ContextReport,
        )
        return report

    def format_text(self, report: ContextReport) -> str:
        """Format a context report as human-readable text."""
        lines: list[str] = [
            "=" * 60,
            "RepoCtx Guard — Task Context Report",
            "=" * 60,
            "",
            "Related Modules:",
        ]
        for m in report.related_modules:
            lines.append(f"  • {m}")
        if not report.related_modules:
            lines.append("  (none identified)")

        lines.extend(["", "Key Files:"])
        for f in report.key_files:
            lines.append(f"  • {f}")
        if not report.key_files:
            lines.append("  (none identified)")

        lines.extend(["", "Reusable Capabilities:"])
        for c in report.reusable_capabilities:
            lines.append(f"  • {c}")
        if not report.reusable_capabilities:
            lines.append("  (none identified)")

        lines.extend(["", "Protected Cores (DO NOT MODIFY):"])
        for p in report.protected_cores:
            lines.append(f"  ⚠ {p}")
        if not report.protected_cores:
            lines.append("  (none identified)")

        lines.extend(["", "Risk Points:"])
        for r in report.risk_points:
            lines.append(f"  ! {r}")
        if not report.risk_points:
            lines.append("  (none identified)")

        lines.extend(["", "Suggested Tests:"])
        for t in report.suggested_tests:
            lines.append(f"  • {t}")
        if not report.suggested_tests:
            lines.append("  (none identified)")

        lines.extend(["", "=" * 60])
        return "\n".join(lines)
